// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arr32`

/// Ed25519 keypair generation. Returns (public_key, private_key), both
/// 32 bytes.
Future<Keypair> generateKeypair() =>
    RustLib.instance.api.crateApiCryptoGenerateKeypair();

Future<Uint8List> blake2B256({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoBlake2B256(data: data);

/// Derive the BLAKE2b-256(public_key) → UUID hex identifier.
Future<String> userIdFromPublicKey({required List<int> publicKey}) =>
    RustLib.instance.api
        .crateApiCryptoUserIdFromPublicKey(publicKey: publicKey);

Future<Uint8List> signMessage(
        {required List<int> message, required List<int> privateKey}) =>
    RustLib.instance.api
        .crateApiCryptoSignMessage(message: message, privateKey: privateKey);

Future<bool> verifySignature(
        {required List<int> message,
        required List<int> signature,
        required List<int> publicKey}) =>
    RustLib.instance.api.crateApiCryptoVerifySignature(
        message: message, signature: signature, publicKey: publicKey);

class Keypair {
  final Uint8List publicKey;
  final Uint8List privateKey;

  const Keypair({
    required this.publicKey,
    required this.privateKey,
  });

  @override
  int get hashCode => publicKey.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Keypair &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          privateKey == other.privateKey;
}
