// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arr32`, `split_seed`

Future<Uint8List> buildAndSignTransaction(
        {required TransactionInput input, required List<int> privateKey}) =>
    RustLib.instance.api.crateApiTransactionsBuildAndSignTransaction(
        input: input, privateKey: privateKey);

Future<TransactionView> decodeTransaction({required List<int> cbor}) =>
    RustLib.instance.api.crateApiTransactionsDecodeTransaction(cbor: cbor);

Future<Uint8List> deriveNextNonce(
        {required List<int> prevNonce,
        required List<int> hardwareSeed,
        required BigInt counter}) =>
    RustLib.instance.api.crateApiTransactionsDeriveNextNonce(
        prevNonce: prevNonce, hardwareSeed: hardwareSeed, counter: counter);

/// Plain-Old-Data input shape. flutter_rust_bridge generates a Dart
/// class with matching fields.
class TransactionInput {
  final Uint8List fromPublicKey;
  final Uint8List toPublicKey;
  final PlatformInt64 amountMicroOwc;
  final String currencyContext;
  final String fxRateSnapshot;
  final int channel;
  final String memo;
  final String deviceId;
  final Uint8List previousNonce;
  final Uint8List currentNonce;
  final double latitude;
  final double longitude;
  final int locationAccuracyMeters;
  final int locationSource;

  const TransactionInput({
    required this.fromPublicKey,
    required this.toPublicKey,
    required this.amountMicroOwc,
    required this.currencyContext,
    required this.fxRateSnapshot,
    required this.channel,
    required this.memo,
    required this.deviceId,
    required this.previousNonce,
    required this.currentNonce,
    required this.latitude,
    required this.longitude,
    required this.locationAccuracyMeters,
    required this.locationSource,
  });

  @override
  int get hashCode =>
      fromPublicKey.hashCode ^
      toPublicKey.hashCode ^
      amountMicroOwc.hashCode ^
      currencyContext.hashCode ^
      fxRateSnapshot.hashCode ^
      channel.hashCode ^
      memo.hashCode ^
      deviceId.hashCode ^
      previousNonce.hashCode ^
      currentNonce.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      locationAccuracyMeters.hashCode ^
      locationSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionInput &&
          runtimeType == other.runtimeType &&
          fromPublicKey == other.fromPublicKey &&
          toPublicKey == other.toPublicKey &&
          amountMicroOwc == other.amountMicroOwc &&
          currencyContext == other.currencyContext &&
          fxRateSnapshot == other.fxRateSnapshot &&
          channel == other.channel &&
          memo == other.memo &&
          deviceId == other.deviceId &&
          previousNonce == other.previousNonce &&
          currentNonce == other.currentNonce &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          locationAccuracyMeters == other.locationAccuracyMeters &&
          locationSource == other.locationSource;
}

class TransactionView {
  final String transactionId;
  final Uint8List fromPublicKey;
  final Uint8List toPublicKey;
  final PlatformInt64 amountMicroOwc;
  final String currencyContext;
  final PlatformInt64 timestampUtc;
  final String memo;
  final int channel;
  final String deviceId;
  final bool signatureValid;

  const TransactionView({
    required this.transactionId,
    required this.fromPublicKey,
    required this.toPublicKey,
    required this.amountMicroOwc,
    required this.currencyContext,
    required this.timestampUtc,
    required this.memo,
    required this.channel,
    required this.deviceId,
    required this.signatureValid,
  });

  @override
  int get hashCode =>
      transactionId.hashCode ^
      fromPublicKey.hashCode ^
      toPublicKey.hashCode ^
      amountMicroOwc.hashCode ^
      currencyContext.hashCode ^
      timestampUtc.hashCode ^
      memo.hashCode ^
      channel.hashCode ^
      deviceId.hashCode ^
      signatureValid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionView &&
          runtimeType == other.runtimeType &&
          transactionId == other.transactionId &&
          fromPublicKey == other.fromPublicKey &&
          toPublicKey == other.toPublicKey &&
          amountMicroOwc == other.amountMicroOwc &&
          currencyContext == other.currencyContext &&
          timestampUtc == other.timestampUtc &&
          memo == other.memo &&
          channel == other.channel &&
          deviceId == other.deviceId &&
          signatureValid == other.signatureValid;
}
