// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `propose`, `select_aid`

Future<String> qrEncode({required List<int> cbor}) =>
    RustLib.instance.api.crateApiWireQrEncode(cbor: cbor);

Future<Uint8List> qrDecode({required String qr}) =>
    RustLib.instance.api.crateApiWireQrDecode(qr: qr);

/// Build the ISO 7816-4 APDU frames for an NFC HCE exchange. Returns a
/// list of C-APDUs the reader should send in order.
Future<List<Uint8List>> buildNfcApdus({required List<int> cbor}) =>
    RustLib.instance.api.crateApiWireBuildNfcApdus(cbor: cbor);
