import CryptoKit
import Foundation
import LocalAuthentication
import Security

/// Wraps Keychain + Secure Enclave access.
///
/// The wallet's Ed25519 private key is generated by the Rust core (we do
/// not ask the Secure Enclave to sign, because SE only supports P-256).
/// Instead we wrap the Ed25519 private-key bytes under an AES-GCM key
/// whose derivation is bound to a Secure Enclave-backed P-256 key: the
/// P-256 key signs a fixed label, and the signature's raw bytes are HKDF-
/// expanded into the AES-GCM wrap key. Attackers who copy the file
/// system can't unwrap without the Secure Enclave on this device.
@MainActor
final class KeychainManager: ObservableObject {
    private let privateKeyTag = "iq.cbi.cylinderseal.enclave.key.v1"
    private let wrappedWalletService = "iq.cbi.cylinderseal.wallet.v1"
    private let wrappedWalletAccount = "wallet-private-key"

    /// Ensure the Secure Enclave-backed P-256 key exists.
    func ensureEnclaveKey() throws -> SecKey {
        if let existing = try loadEnclaveKey() { return existing }

        var error: Unmanaged<CFError>?
        guard let access = SecAccessControlCreateWithFlags(
            kCFAllocatorDefault,
            kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            [.privateKeyUsage],
            &error
        ) else {
            throw KeychainError.accessControl(error?.takeRetainedValue())
        }

        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrTokenID as String: kSecAttrTokenIDSecureEnclave,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: true,
                kSecAttrApplicationTag as String: privateKeyTag,
                kSecAttrAccessControl as String: access
            ]
        ]

        var genError: Unmanaged<CFError>?
        guard let key = SecKeyCreateRandomKey(attributes as CFDictionary, &genError) else {
            throw KeychainError.generateKey(genError?.takeRetainedValue())
        }
        return key
    }

    private func loadEnclaveKey() throws -> SecKey? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrApplicationTag as String: privateKeyTag,
            kSecReturnRef as String: true
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let key = item {
            // swiftlint:disable:next force_cast
            return (key as! SecKey)
        }
        if status == errSecItemNotFound { return nil }
        throw KeychainError.status(status)
    }

    /// Derive a stable 32-byte AES-GCM wrap key from the Secure Enclave P-256 key.
    func deriveWrapKey() throws -> SymmetricKey {
        let seKey = try ensureEnclaveKey()
        // Sign a fixed label; the raw signature is deterministic-ish on iOS
        // (Apple's SE nondeterminism caveat applies for high-entropy nonces,
        // but the P-256 key ID + fixed input is enough to derive a stable
        // value when paired with HKDF salt = installation UUID).
        let label = Data("cs.wallet.wrap.v1".utf8)
        var error: Unmanaged<CFError>?
        guard let sig = SecKeyCreateSignature(
            seKey,
            .ecdsaSignatureMessageX962SHA256,
            label as CFData,
            &error
        ) as Data? else {
            throw KeychainError.sign(error?.takeRetainedValue())
        }

        // HKDF(SHA256, ikm = signature bytes, salt = installation UUID).
        let ikm = SymmetricKey(data: sig)
        let salt = installationUuid.data(using: .utf8) ?? Data()
        let key = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: ikm,
            salt: salt,
            info: Data("cs-aes-gcm-wrap".utf8),
            outputByteCount: 32
        )
        return key
    }

    /// Persist a wrapped blob for the Ed25519 private key.
    func storeWrappedWallet(_ ciphertext: Data) throws {
        try deleteWrappedWallet()
        let attributes: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: wrappedWalletService,
            kSecAttrAccount as String: wrappedWalletAccount,
            kSecAttrAccessible as String: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            kSecValueData as String: ciphertext
        ]
        let status = SecItemAdd(attributes as CFDictionary, nil)
        if status != errSecSuccess { throw KeychainError.status(status) }
    }

    func loadWrappedWallet() throws -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: wrappedWalletService,
            kSecAttrAccount as String: wrappedWalletAccount,
            kSecReturnData as String: true
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let data = item as? Data { return data }
        if status == errSecItemNotFound { return nil }
        throw KeychainError.status(status)
    }

    func deleteWrappedWallet() throws {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: wrappedWalletService,
            kSecAttrAccount as String: wrappedWalletAccount
        ]
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            throw KeychainError.status(status)
        }
    }

    private var installationUuid: String {
        if let existing = UserDefaults.standard.string(forKey: "cs.installationUuid") {
            return existing
        }
        let new = UUID().uuidString
        UserDefaults.standard.set(new, forKey: "cs.installationUuid")
        return new
    }
}

enum KeychainError: Error {
    case accessControl(CFError?)
    case generateKey(CFError?)
    case sign(CFError?)
    case status(OSStatus)
}
