// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto.dart';
import 'api/transactions.dart';
import 'api/wire.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  TransactionInput dco_decode_box_autoadd_transaction_input(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Keypair dco_decode_keypair(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  TransactionInput dco_decode_transaction_input(dynamic raw);

  @protected
  TransactionView dco_decode_transaction_view(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  TransactionInput sse_decode_box_autoadd_transaction_input(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  TransactionInput sse_decode_transaction_input(SseDeserializer deserializer);

  @protected
  TransactionView sse_decode_transaction_view(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_transaction_input(TransactionInput raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_transaction_input(raw);
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_keypair(Keypair raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.publicKey),
      cst_encode_list_prim_u_8_strict(raw.privateKey)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_u_8_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_transaction_input(TransactionInput raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.fromPublicKey),
      cst_encode_list_prim_u_8_strict(raw.toPublicKey),
      cst_encode_i_64(raw.amountMicroOwc),
      cst_encode_String(raw.currencyContext),
      cst_encode_String(raw.fxRateSnapshot),
      cst_encode_i_32(raw.channel),
      cst_encode_String(raw.memo),
      cst_encode_String(raw.deviceId),
      cst_encode_list_prim_u_8_strict(raw.previousNonce),
      cst_encode_list_prim_u_8_strict(raw.currentNonce),
      cst_encode_f_64(raw.latitude),
      cst_encode_f_64(raw.longitude),
      cst_encode_i_32(raw.locationAccuracyMeters),
      cst_encode_i_32(raw.locationSource)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_transaction_view(TransactionView raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.transactionId),
      cst_encode_list_prim_u_8_strict(raw.fromPublicKey),
      cst_encode_list_prim_u_8_strict(raw.toPublicKey),
      cst_encode_i_64(raw.amountMicroOwc),
      cst_encode_String(raw.currencyContext),
      cst_encode_i_64(raw.timestampUtc),
      cst_encode_String(raw.memo),
      cst_encode_i_32(raw.channel),
      cst_encode_String(raw.deviceId),
      cst_encode_bool(raw.signatureValid)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transaction_input(
      TransactionInput self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_input(
      TransactionInput self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_view(
      TransactionView self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__crypto__blake2b_256(
          NativePortType port_, JSAny data) =>
      wasmModule.wire__crate__api__crypto__blake2b_256(port_, data);

  void wire__crate__api__transactions__build_and_sign_transaction(
          NativePortType port_, JSAny input, JSAny private_key) =>
      wasmModule.wire__crate__api__transactions__build_and_sign_transaction(
          port_, input, private_key);

  void wire__crate__api__wire__build_nfc_apdus(
          NativePortType port_, JSAny cbor) =>
      wasmModule.wire__crate__api__wire__build_nfc_apdus(port_, cbor);

  void wire__crate__api__transactions__decode_transaction(
          NativePortType port_, JSAny cbor) =>
      wasmModule.wire__crate__api__transactions__decode_transaction(
          port_, cbor);

  void wire__crate__api__transactions__derive_next_nonce(NativePortType port_,
          JSAny prev_nonce, JSAny hardware_seed, JSAny counter) =>
      wasmModule.wire__crate__api__transactions__derive_next_nonce(
          port_, prev_nonce, hardware_seed, counter);

  void wire__crate__api__crypto__generate_keypair(NativePortType port_) =>
      wasmModule.wire__crate__api__crypto__generate_keypair(port_);

  void wire__crate__api__wire__qr_decode(NativePortType port_, String qr) =>
      wasmModule.wire__crate__api__wire__qr_decode(port_, qr);

  void wire__crate__api__wire__qr_encode(NativePortType port_, JSAny cbor) =>
      wasmModule.wire__crate__api__wire__qr_encode(port_, cbor);

  void wire__crate__api__crypto__sign_message(
          NativePortType port_, JSAny message, JSAny private_key) =>
      wasmModule.wire__crate__api__crypto__sign_message(
          port_, message, private_key);

  void wire__crate__api__crypto__user_id_from_public_key(
          NativePortType port_, JSAny public_key) =>
      wasmModule.wire__crate__api__crypto__user_id_from_public_key(
          port_, public_key);

  void wire__crate__api__crypto__verify_signature(NativePortType port_,
          JSAny message, JSAny signature, JSAny public_key) =>
      wasmModule.wire__crate__api__crypto__verify_signature(
          port_, message, signature, public_key);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__crypto__blake2b_256(
      NativePortType port_, JSAny data);

  external void wire__crate__api__transactions__build_and_sign_transaction(
      NativePortType port_, JSAny input, JSAny private_key);

  external void wire__crate__api__wire__build_nfc_apdus(
      NativePortType port_, JSAny cbor);

  external void wire__crate__api__transactions__decode_transaction(
      NativePortType port_, JSAny cbor);

  external void wire__crate__api__transactions__derive_next_nonce(
      NativePortType port_,
      JSAny prev_nonce,
      JSAny hardware_seed,
      JSAny counter);

  external void wire__crate__api__crypto__generate_keypair(
      NativePortType port_);

  external void wire__crate__api__wire__qr_decode(
      NativePortType port_, String qr);

  external void wire__crate__api__wire__qr_encode(
      NativePortType port_, JSAny cbor);

  external void wire__crate__api__crypto__sign_message(
      NativePortType port_, JSAny message, JSAny private_key);

  external void wire__crate__api__crypto__user_id_from_public_key(
      NativePortType port_, JSAny public_key);

  external void wire__crate__api__crypto__verify_signature(
      NativePortType port_, JSAny message, JSAny signature, JSAny public_key);
}
