// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/transactions.dart';
import 'api/wire.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  TransactionInput dco_decode_box_autoadd_transaction_input(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Keypair dco_decode_keypair(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  TransactionInput dco_decode_transaction_input(dynamic raw);

  @protected
  TransactionView dco_decode_transaction_view(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  TransactionInput sse_decode_box_autoadd_transaction_input(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  TransactionInput sse_decode_transaction_input(SseDeserializer deserializer);

  @protected
  TransactionView sse_decode_transaction_view(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_transaction_input>
      cst_encode_box_autoadd_transaction_input(TransactionInput raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_transaction_input();
    cst_api_fill_to_wire_transaction_input(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
      cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_list_prim_u_8_strict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_list_prim_u_8_strict(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_transaction_input(
      TransactionInput apiObj,
      ffi.Pointer<wire_cst_transaction_input> wireObj) {
    cst_api_fill_to_wire_transaction_input(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_keypair(Keypair apiObj, wire_cst_keypair wireObj) {
    wireObj.public_key = cst_encode_list_prim_u_8_strict(apiObj.publicKey);
    wireObj.private_key = cst_encode_list_prim_u_8_strict(apiObj.privateKey);
  }

  @protected
  void cst_api_fill_to_wire_transaction_input(
      TransactionInput apiObj, wire_cst_transaction_input wireObj) {
    wireObj.from_public_key =
        cst_encode_list_prim_u_8_strict(apiObj.fromPublicKey);
    wireObj.to_public_key = cst_encode_list_prim_u_8_strict(apiObj.toPublicKey);
    wireObj.amount_micro_owc = cst_encode_i_64(apiObj.amountMicroOwc);
    wireObj.currency_context = cst_encode_String(apiObj.currencyContext);
    wireObj.fx_rate_snapshot = cst_encode_String(apiObj.fxRateSnapshot);
    wireObj.channel = cst_encode_i_32(apiObj.channel);
    wireObj.memo = cst_encode_String(apiObj.memo);
    wireObj.device_id = cst_encode_String(apiObj.deviceId);
    wireObj.previous_nonce =
        cst_encode_list_prim_u_8_strict(apiObj.previousNonce);
    wireObj.current_nonce =
        cst_encode_list_prim_u_8_strict(apiObj.currentNonce);
    wireObj.latitude = cst_encode_f_64(apiObj.latitude);
    wireObj.longitude = cst_encode_f_64(apiObj.longitude);
    wireObj.location_accuracy_meters =
        cst_encode_i_32(apiObj.locationAccuracyMeters);
    wireObj.location_source = cst_encode_i_32(apiObj.locationSource);
  }

  @protected
  void cst_api_fill_to_wire_transaction_view(
      TransactionView apiObj, wire_cst_transaction_view wireObj) {
    wireObj.transaction_id = cst_encode_String(apiObj.transactionId);
    wireObj.from_public_key =
        cst_encode_list_prim_u_8_strict(apiObj.fromPublicKey);
    wireObj.to_public_key = cst_encode_list_prim_u_8_strict(apiObj.toPublicKey);
    wireObj.amount_micro_owc = cst_encode_i_64(apiObj.amountMicroOwc);
    wireObj.currency_context = cst_encode_String(apiObj.currencyContext);
    wireObj.timestamp_utc = cst_encode_i_64(apiObj.timestampUtc);
    wireObj.memo = cst_encode_String(apiObj.memo);
    wireObj.channel = cst_encode_i_32(apiObj.channel);
    wireObj.device_id = cst_encode_String(apiObj.deviceId);
    wireObj.signature_valid = cst_encode_bool(apiObj.signatureValid);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transaction_input(
      TransactionInput self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_input(
      TransactionInput self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_view(
      TransactionView self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__crypto__blake2b_256(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__crypto__blake2b_256(
      port_,
      data,
    );
  }

  late final _wire__crate__api__crypto__blake2b_256Ptr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__crypto__blake2b_256');
  late final _wire__crate__api__crypto__blake2b_256 =
      _wire__crate__api__crypto__blake2b_256Ptr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__transactions__build_and_sign_transaction(
    int port_,
    ffi.Pointer<wire_cst_transaction_input> input,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> private_key,
  ) {
    return _wire__crate__api__transactions__build_and_sign_transaction(
      port_,
      input,
      private_key,
    );
  }

  late final _wire__crate__api__transactions__build_and_sign_transactionPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(
                      ffi.Int64,
                      ffi.Pointer<wire_cst_transaction_input>,
                      ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
          'frbgen_cylinder_seal_wire__crate__api__transactions__build_and_sign_transaction');
  late final _wire__crate__api__transactions__build_and_sign_transaction =
      _wire__crate__api__transactions__build_and_sign_transactionPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_transaction_input>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__wire__build_nfc_apdus(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> cbor,
  ) {
    return _wire__crate__api__wire__build_nfc_apdus(
      port_,
      cbor,
    );
  }

  late final _wire__crate__api__wire__build_nfc_apdusPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__wire__build_nfc_apdus');
  late final _wire__crate__api__wire__build_nfc_apdus =
      _wire__crate__api__wire__build_nfc_apdusPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__transactions__decode_transaction(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> cbor,
  ) {
    return _wire__crate__api__transactions__decode_transaction(
      port_,
      cbor,
    );
  }

  late final _wire__crate__api__transactions__decode_transactionPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__transactions__decode_transaction');
  late final _wire__crate__api__transactions__decode_transaction =
      _wire__crate__api__transactions__decode_transactionPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__transactions__derive_next_nonce(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> prev_nonce,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> hardware_seed,
    int counter,
  ) {
    return _wire__crate__api__transactions__derive_next_nonce(
      port_,
      prev_nonce,
      hardware_seed,
      counter,
    );
  }

  late final _wire__crate__api__transactions__derive_next_noncePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Uint64)>>(
      'frbgen_cylinder_seal_wire__crate__api__transactions__derive_next_nonce');
  late final _wire__crate__api__transactions__derive_next_nonce =
      _wire__crate__api__transactions__derive_next_noncePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>, int)>();

  void wire__crate__api__crypto__generate_keypair(
    int port_,
  ) {
    return _wire__crate__api__crypto__generate_keypair(
      port_,
    );
  }

  late final _wire__crate__api__crypto__generate_keypairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_cylinder_seal_wire__crate__api__crypto__generate_keypair');
  late final _wire__crate__api__crypto__generate_keypair =
      _wire__crate__api__crypto__generate_keypairPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__wire__qr_decode(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> qr,
  ) {
    return _wire__crate__api__wire__qr_decode(
      port_,
      qr,
    );
  }

  late final _wire__crate__api__wire__qr_decodePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_cylinder_seal_wire__crate__api__wire__qr_decode');
  late final _wire__crate__api__wire__qr_decode =
      _wire__crate__api__wire__qr_decodePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__wire__qr_encode(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> cbor,
  ) {
    return _wire__crate__api__wire__qr_encode(
      port_,
      cbor,
    );
  }

  late final _wire__crate__api__wire__qr_encodePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__wire__qr_encode');
  late final _wire__crate__api__wire__qr_encode =
      _wire__crate__api__wire__qr_encodePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__crypto__sign_message(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> private_key,
  ) {
    return _wire__crate__api__crypto__sign_message(
      port_,
      message,
      private_key,
    );
  }

  late final _wire__crate__api__crypto__sign_messagePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__crypto__sign_message');
  late final _wire__crate__api__crypto__sign_message =
      _wire__crate__api__crypto__sign_messagePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__crypto__user_id_from_public_key(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> public_key,
  ) {
    return _wire__crate__api__crypto__user_id_from_public_key(
      port_,
      public_key,
    );
  }

  late final _wire__crate__api__crypto__user_id_from_public_keyPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__crypto__user_id_from_public_key');
  late final _wire__crate__api__crypto__user_id_from_public_key =
      _wire__crate__api__crypto__user_id_from_public_keyPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  void wire__crate__api__crypto__verify_signature(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> public_key,
  ) {
    return _wire__crate__api__crypto__verify_signature(
      port_,
      message,
      signature,
      public_key,
    );
  }

  late final _wire__crate__api__crypto__verify_signaturePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>)>>(
      'frbgen_cylinder_seal_wire__crate__api__crypto__verify_signature');
  late final _wire__crate__api__crypto__verify_signature =
      _wire__crate__api__crypto__verify_signaturePtr.asFunction<
          void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>)>();

  ffi.Pointer<wire_cst_transaction_input>
      cst_new_box_autoadd_transaction_input() {
    return _cst_new_box_autoadd_transaction_input();
  }

  late final _cst_new_box_autoadd_transaction_inputPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_transaction_input> Function()>>(
      'frbgen_cylinder_seal_cst_new_box_autoadd_transaction_input');
  late final _cst_new_box_autoadd_transaction_input =
      _cst_new_box_autoadd_transaction_inputPtr
          .asFunction<ffi.Pointer<wire_cst_transaction_input> Function()>();

  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
      cst_new_list_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_list_prim_u_8_strictPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(
                  ffi.Int32)>>(
      'frbgen_cylinder_seal_cst_new_list_list_prim_u_8_strict');
  late final _cst_new_list_list_prim_u_8_strict =
      _cst_new_list_list_prim_u_8_strictPtr.asFunction<
          ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(
              ffi.Int32)>>('frbgen_cylinder_seal_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_cylinder_seal_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_transaction_input extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> from_public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> to_public_key;

  @ffi.Int64()
  external int amount_micro_owc;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> currency_context;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> fx_rate_snapshot;

  @ffi.Int32()
  external int channel;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> memo;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> device_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_nonce;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> current_nonce;

  @ffi.Double()
  external double latitude;

  @ffi.Double()
  external double longitude;

  @ffi.Int32()
  external int location_accuracy_meters;

  @ffi.Int32()
  external int location_source;
}

final class wire_cst_list_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_keypair extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key;
}

final class wire_cst_transaction_view extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> transaction_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> from_public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> to_public_key;

  @ffi.Int64()
  external int amount_micro_owc;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> currency_context;

  @ffi.Int64()
  external int timestamp_utc;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> memo;

  @ffi.Int32()
  external int channel;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> device_id;

  @ffi.Bool()
  external bool signature_valid;
}
