// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/transactions.dart';
import 'api/wire.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 1652350690;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'cs_bridge',
    ioDirectory: '../crates/cs-bridge/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiCryptoBlake2B256({required List<int> data});

  Future<Uint8List> crateApiTransactionsBuildAndSignTransaction(
      {required TransactionInput input, required List<int> privateKey});

  Future<List<Uint8List>> crateApiWireBuildNfcApdus({required List<int> cbor});

  Future<TransactionView> crateApiTransactionsDecodeTransaction(
      {required List<int> cbor});

  Future<Uint8List> crateApiTransactionsDeriveNextNonce(
      {required List<int> prevNonce,
      required List<int> hardwareSeed,
      required BigInt counter});

  Future<Keypair> crateApiCryptoGenerateKeypair();

  Future<Uint8List> crateApiWireQrDecode({required String qr});

  Future<String> crateApiWireQrEncode({required List<int> cbor});

  Future<Uint8List> crateApiCryptoSignMessage(
      {required List<int> message, required List<int> privateKey});

  Future<String> crateApiCryptoUserIdFromPublicKey(
      {required List<int> publicKey});

  Future<bool> crateApiCryptoVerifySignature(
      {required List<int> message,
      required List<int> signature,
      required List<int> publicKey});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiCryptoBlake2B256({required List<int> data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(data);
        return wire.wire__crate__api__crypto__blake2b_256(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoBlake2B256ConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoBlake2B256ConstMeta => const TaskConstMeta(
        debugName: "blake2b_256",
        argNames: ["data"],
      );

  @override
  Future<Uint8List> crateApiTransactionsBuildAndSignTransaction(
      {required TransactionInput input, required List<int> privateKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_box_autoadd_transaction_input(input);
        var arg1 = cst_encode_list_prim_u_8_loose(privateKey);
        return wire.wire__crate__api__transactions__build_and_sign_transaction(
            port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiTransactionsBuildAndSignTransactionConstMeta,
      argValues: [input, privateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTransactionsBuildAndSignTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "build_and_sign_transaction",
        argNames: ["input", "privateKey"],
      );

  @override
  Future<List<Uint8List>> crateApiWireBuildNfcApdus({required List<int> cbor}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(cbor);
        return wire.wire__crate__api__wire__build_nfc_apdus(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWireBuildNfcApdusConstMeta,
      argValues: [cbor],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWireBuildNfcApdusConstMeta => const TaskConstMeta(
        debugName: "build_nfc_apdus",
        argNames: ["cbor"],
      );

  @override
  Future<TransactionView> crateApiTransactionsDecodeTransaction(
      {required List<int> cbor}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(cbor);
        return wire.wire__crate__api__transactions__decode_transaction(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_transaction_view,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiTransactionsDecodeTransactionConstMeta,
      argValues: [cbor],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTransactionsDecodeTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "decode_transaction",
        argNames: ["cbor"],
      );

  @override
  Future<Uint8List> crateApiTransactionsDeriveNextNonce(
      {required List<int> prevNonce,
      required List<int> hardwareSeed,
      required BigInt counter}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(prevNonce);
        var arg1 = cst_encode_list_prim_u_8_loose(hardwareSeed);
        var arg2 = cst_encode_u_64(counter);
        return wire.wire__crate__api__transactions__derive_next_nonce(
            port_, arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiTransactionsDeriveNextNonceConstMeta,
      argValues: [prevNonce, hardwareSeed, counter],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTransactionsDeriveNextNonceConstMeta =>
      const TaskConstMeta(
        debugName: "derive_next_nonce",
        argNames: ["prevNonce", "hardwareSeed", "counter"],
      );

  @override
  Future<Keypair> crateApiCryptoGenerateKeypair() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__crypto__generate_keypair(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_keypair,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoGenerateKeypairConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_keypair",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiWireQrDecode({required String qr}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(qr);
        return wire.wire__crate__api__wire__qr_decode(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiWireQrDecodeConstMeta,
      argValues: [qr],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWireQrDecodeConstMeta => const TaskConstMeta(
        debugName: "qr_decode",
        argNames: ["qr"],
      );

  @override
  Future<String> crateApiWireQrEncode({required List<int> cbor}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(cbor);
        return wire.wire__crate__api__wire__qr_encode(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiWireQrEncodeConstMeta,
      argValues: [cbor],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWireQrEncodeConstMeta => const TaskConstMeta(
        debugName: "qr_encode",
        argNames: ["cbor"],
      );

  @override
  Future<Uint8List> crateApiCryptoSignMessage(
      {required List<int> message, required List<int> privateKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(message);
        var arg1 = cst_encode_list_prim_u_8_loose(privateKey);
        return wire.wire__crate__api__crypto__sign_message(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoSignMessageConstMeta,
      argValues: [message, privateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSignMessageConstMeta => const TaskConstMeta(
        debugName: "sign_message",
        argNames: ["message", "privateKey"],
      );

  @override
  Future<String> crateApiCryptoUserIdFromPublicKey(
      {required List<int> publicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(publicKey);
        return wire.wire__crate__api__crypto__user_id_from_public_key(
            port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoUserIdFromPublicKeyConstMeta,
      argValues: [publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoUserIdFromPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "user_id_from_public_key",
        argNames: ["publicKey"],
      );

  @override
  Future<bool> crateApiCryptoVerifySignature(
      {required List<int> message,
      required List<int> signature,
      required List<int> publicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_prim_u_8_loose(message);
        var arg1 = cst_encode_list_prim_u_8_loose(signature);
        var arg2 = cst_encode_list_prim_u_8_loose(publicKey);
        return wire.wire__crate__api__crypto__verify_signature(
            port_, arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: dco_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoVerifySignatureConstMeta,
      argValues: [message, signature, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoVerifySignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_signature",
        argNames: ["message", "signature", "publicKey"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TransactionInput dco_decode_box_autoadd_transaction_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transaction_input(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Keypair dco_decode_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Keypair(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      privateKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  TransactionInput dco_decode_transaction_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return TransactionInput(
      fromPublicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      toPublicKey: dco_decode_list_prim_u_8_strict(arr[1]),
      amountMicroOwc: dco_decode_i_64(arr[2]),
      currencyContext: dco_decode_String(arr[3]),
      fxRateSnapshot: dco_decode_String(arr[4]),
      channel: dco_decode_i_32(arr[5]),
      memo: dco_decode_String(arr[6]),
      deviceId: dco_decode_String(arr[7]),
      previousNonce: dco_decode_list_prim_u_8_strict(arr[8]),
      currentNonce: dco_decode_list_prim_u_8_strict(arr[9]),
      latitude: dco_decode_f_64(arr[10]),
      longitude: dco_decode_f_64(arr[11]),
      locationAccuracyMeters: dco_decode_i_32(arr[12]),
      locationSource: dco_decode_i_32(arr[13]),
    );
  }

  @protected
  TransactionView dco_decode_transaction_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TransactionView(
      transactionId: dco_decode_String(arr[0]),
      fromPublicKey: dco_decode_list_prim_u_8_strict(arr[1]),
      toPublicKey: dco_decode_list_prim_u_8_strict(arr[2]),
      amountMicroOwc: dco_decode_i_64(arr[3]),
      currencyContext: dco_decode_String(arr[4]),
      timestampUtc: dco_decode_i_64(arr[5]),
      memo: dco_decode_String(arr[6]),
      channel: dco_decode_i_32(arr[7]),
      deviceId: dco_decode_String(arr[8]),
      signatureValid: dco_decode_bool(arr[9]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TransactionInput sse_decode_box_autoadd_transaction_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transaction_input(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_privateKey = sse_decode_list_prim_u_8_strict(deserializer);
    return Keypair(publicKey: var_publicKey, privateKey: var_privateKey);
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  TransactionInput sse_decode_transaction_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fromPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_toPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_amountMicroOwc = sse_decode_i_64(deserializer);
    var var_currencyContext = sse_decode_String(deserializer);
    var var_fxRateSnapshot = sse_decode_String(deserializer);
    var var_channel = sse_decode_i_32(deserializer);
    var var_memo = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_previousNonce = sse_decode_list_prim_u_8_strict(deserializer);
    var var_currentNonce = sse_decode_list_prim_u_8_strict(deserializer);
    var var_latitude = sse_decode_f_64(deserializer);
    var var_longitude = sse_decode_f_64(deserializer);
    var var_locationAccuracyMeters = sse_decode_i_32(deserializer);
    var var_locationSource = sse_decode_i_32(deserializer);
    return TransactionInput(
        fromPublicKey: var_fromPublicKey,
        toPublicKey: var_toPublicKey,
        amountMicroOwc: var_amountMicroOwc,
        currencyContext: var_currencyContext,
        fxRateSnapshot: var_fxRateSnapshot,
        channel: var_channel,
        memo: var_memo,
        deviceId: var_deviceId,
        previousNonce: var_previousNonce,
        currentNonce: var_currentNonce,
        latitude: var_latitude,
        longitude: var_longitude,
        locationAccuracyMeters: var_locationAccuracyMeters,
        locationSource: var_locationSource);
  }

  @protected
  TransactionView sse_decode_transaction_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transactionId = sse_decode_String(deserializer);
    var var_fromPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_toPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_amountMicroOwc = sse_decode_i_64(deserializer);
    var var_currencyContext = sse_decode_String(deserializer);
    var var_timestampUtc = sse_decode_i_64(deserializer);
    var var_memo = sse_decode_String(deserializer);
    var var_channel = sse_decode_i_32(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_signatureValid = sse_decode_bool(deserializer);
    return TransactionView(
        transactionId: var_transactionId,
        fromPublicKey: var_fromPublicKey,
        toPublicKey: var_toPublicKey,
        amountMicroOwc: var_amountMicroOwc,
        currencyContext: var_currencyContext,
        timestampUtc: var_timestampUtc,
        memo: var_memo,
        channel: var_channel,
        deviceId: var_deviceId,
        signatureValid: var_signatureValid);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_transaction_input(
      TransactionInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transaction_input(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.privateKey, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_transaction_input(
      TransactionInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.fromPublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.toPublicKey, serializer);
    sse_encode_i_64(self.amountMicroOwc, serializer);
    sse_encode_String(self.currencyContext, serializer);
    sse_encode_String(self.fxRateSnapshot, serializer);
    sse_encode_i_32(self.channel, serializer);
    sse_encode_String(self.memo, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_list_prim_u_8_strict(self.previousNonce, serializer);
    sse_encode_list_prim_u_8_strict(self.currentNonce, serializer);
    sse_encode_f_64(self.latitude, serializer);
    sse_encode_f_64(self.longitude, serializer);
    sse_encode_i_32(self.locationAccuracyMeters, serializer);
    sse_encode_i_32(self.locationSource, serializer);
  }

  @protected
  void sse_encode_transaction_view(
      TransactionView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transactionId, serializer);
    sse_encode_list_prim_u_8_strict(self.fromPublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.toPublicKey, serializer);
    sse_encode_i_64(self.amountMicroOwc, serializer);
    sse_encode_String(self.currencyContext, serializer);
    sse_encode_i_64(self.timestampUtc, serializer);
    sse_encode_String(self.memo, serializer);
    sse_encode_i_32(self.channel, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_bool(self.signatureValid, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
