// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = DcoCodec,
                    default_rust_opaque = RustOpaqueNom,
                    default_rust_auto_opaque = RustAutoOpaqueNom,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.7.0";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1652350690;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__crypto__blake2b_256_impl(port_: flutter_rust_bridge::for_generated::MessagePort,data: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "blake2b_256", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_data = data.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::crypto::blake2b_256(api_data))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__transactions__build_and_sign_transaction_impl(port_: flutter_rust_bridge::for_generated::MessagePort,input: impl CstDecode<crate::api::transactions::TransactionInput>,private_key: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "build_and_sign_transaction", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_input = input.cst_decode();let api_private_key = private_key.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::transactions::build_and_sign_transaction(api_input, api_private_key)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__wire__build_nfc_apdus_impl(port_: flutter_rust_bridge::for_generated::MessagePort,cbor: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "build_nfc_apdus", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_cbor = cbor.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::wire::build_nfc_apdus(api_cbor))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__transactions__decode_transaction_impl(port_: flutter_rust_bridge::for_generated::MessagePort,cbor: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "decode_transaction", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_cbor = cbor.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::transactions::decode_transaction(api_cbor)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__transactions__derive_next_nonce_impl(port_: flutter_rust_bridge::for_generated::MessagePort,prev_nonce: impl CstDecode<Vec<u8>>,hardware_seed: impl CstDecode<Vec<u8>>,counter: impl CstDecode<u64>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "derive_next_nonce", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_prev_nonce = prev_nonce.cst_decode();let api_hardware_seed = hardware_seed.cst_decode();let api_counter = counter.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::transactions::derive_next_nonce(api_prev_nonce, api_hardware_seed, api_counter)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__crypto__generate_keypair_impl(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "generate_keypair", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {  move |context|  {
                    transform_result_dco::<_, _, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::crypto::generate_keypair())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__wire__qr_decode_impl(port_: flutter_rust_bridge::for_generated::MessagePort,qr: impl CstDecode<String>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "qr_decode", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_qr = qr.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::wire::qr_decode(api_qr)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__wire__qr_encode_impl(port_: flutter_rust_bridge::for_generated::MessagePort,cbor: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "qr_encode", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_cbor = cbor.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::wire::qr_encode(api_cbor)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__crypto__sign_message_impl(port_: flutter_rust_bridge::for_generated::MessagePort,message: impl CstDecode<Vec<u8>>,private_key: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "sign_message", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_message = message.cst_decode();let api_private_key = private_key.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::crypto::sign_message(api_message, api_private_key)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__crypto__user_id_from_public_key_impl(port_: flutter_rust_bridge::for_generated::MessagePort,public_key: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "user_id_from_public_key", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_public_key = public_key.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::crypto::user_id_from_public_key(api_public_key)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__crypto__verify_signature_impl(port_: flutter_rust_bridge::for_generated::MessagePort,message: impl CstDecode<Vec<u8>>,signature: impl CstDecode<Vec<u8>>,public_key: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "verify_signature", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_message = message.cst_decode();let api_signature = signature.cst_decode();let api_public_key = public_key.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::api::crypto::verify_signature(api_message, api_signature, api_public_key)?;   Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust

impl CstDecode<bool> for bool {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> bool {
                self
            }
        }impl CstDecode<f64> for f64 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> f64 {
                self
            }
        }impl CstDecode<i32> for i32 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> i32 {
                self
            }
        }impl CstDecode<i64> for i64 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> i64 {
                self
            }
        }impl CstDecode<u64> for u64 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u64 {
                self
            }
        }impl CstDecode<u8> for u8 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u8 {
                self
            }
        }
                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_f64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for crate::api::crypto::Keypair {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_publicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_privateKey = <Vec<u8>>::sse_decode(deserializer);
return crate::api::crypto::Keypair{public_key: var_publicKey, private_key: var_privateKey};}
                }
                
                impl SseDecode for Vec<Vec<u8>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<Vec<u8>>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::api::transactions::TransactionInput {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_fromPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_toPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_amountMicroOwc = <i64>::sse_decode(deserializer);
let mut var_currencyContext = <String>::sse_decode(deserializer);
let mut var_fxRateSnapshot = <String>::sse_decode(deserializer);
let mut var_channel = <i32>::sse_decode(deserializer);
let mut var_memo = <String>::sse_decode(deserializer);
let mut var_deviceId = <String>::sse_decode(deserializer);
let mut var_previousNonce = <Vec<u8>>::sse_decode(deserializer);
let mut var_currentNonce = <Vec<u8>>::sse_decode(deserializer);
let mut var_latitude = <f64>::sse_decode(deserializer);
let mut var_longitude = <f64>::sse_decode(deserializer);
let mut var_locationAccuracyMeters = <i32>::sse_decode(deserializer);
let mut var_locationSource = <i32>::sse_decode(deserializer);
return crate::api::transactions::TransactionInput{from_public_key: var_fromPublicKey, to_public_key: var_toPublicKey, amount_micro_owc: var_amountMicroOwc, currency_context: var_currencyContext, fx_rate_snapshot: var_fxRateSnapshot, channel: var_channel, memo: var_memo, device_id: var_deviceId, previous_nonce: var_previousNonce, current_nonce: var_currentNonce, latitude: var_latitude, longitude: var_longitude, location_accuracy_meters: var_locationAccuracyMeters, location_source: var_locationSource};}
                }
                
                impl SseDecode for crate::api::transactions::TransactionView {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_transactionId = <String>::sse_decode(deserializer);
let mut var_fromPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_toPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_amountMicroOwc = <i64>::sse_decode(deserializer);
let mut var_currencyContext = <String>::sse_decode(deserializer);
let mut var_timestampUtc = <i64>::sse_decode(deserializer);
let mut var_memo = <String>::sse_decode(deserializer);
let mut var_channel = <i32>::sse_decode(deserializer);
let mut var_deviceId = <String>::sse_decode(deserializer);
let mut var_signatureValid = <bool>::sse_decode(deserializer);
return crate::api::transactions::TransactionView{transaction_id: var_transactionId, from_public_key: var_fromPublicKey, to_public_key: var_toPublicKey, amount_micro_owc: var_amountMicroOwc, currency_context: var_currencyContext, timestamp_utc: var_timestampUtc, memo: var_memo, channel: var_channel, device_id: var_deviceId, signature_valid: var_signatureValid};}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::crypto::Keypair {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.public_key.into_into_dart().into_dart(),
self.private_key.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::crypto::Keypair {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::crypto::Keypair> for crate::api::crypto::Keypair {
            fn into_into_dart(self) -> crate::api::crypto::Keypair {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::transactions::TransactionInput {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.from_public_key.into_into_dart().into_dart(),
self.to_public_key.into_into_dart().into_dart(),
self.amount_micro_owc.into_into_dart().into_dart(),
self.currency_context.into_into_dart().into_dart(),
self.fx_rate_snapshot.into_into_dart().into_dart(),
self.channel.into_into_dart().into_dart(),
self.memo.into_into_dart().into_dart(),
self.device_id.into_into_dart().into_dart(),
self.previous_nonce.into_into_dart().into_dart(),
self.current_nonce.into_into_dart().into_dart(),
self.latitude.into_into_dart().into_dart(),
self.longitude.into_into_dart().into_dart(),
self.location_accuracy_meters.into_into_dart().into_dart(),
self.location_source.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::transactions::TransactionInput {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::TransactionInput> for crate::api::transactions::TransactionInput {
            fn into_into_dart(self) -> crate::api::transactions::TransactionInput {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::transactions::TransactionView {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.transaction_id.into_into_dart().into_dart(),
self.from_public_key.into_into_dart().into_dart(),
self.to_public_key.into_into_dart().into_dart(),
self.amount_micro_owc.into_into_dart().into_dart(),
self.currency_context.into_into_dart().into_dart(),
self.timestamp_utc.into_into_dart().into_dart(),
self.memo.into_into_dart().into_dart(),
self.channel.into_into_dart().into_dart(),
self.device_id.into_into_dart().into_dart(),
self.signature_valid.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::transactions::TransactionView {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::TransactionView> for crate::api::transactions::TransactionView {
            fn into_into_dart(self) -> crate::api::transactions::TransactionView {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_f64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for crate::api::crypto::Keypair {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.public_key, serializer);
<Vec<u8>>::sse_encode(self.private_key, serializer);}
                }
                
                impl SseEncode for Vec<Vec<u8>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <Vec<u8>>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::api::transactions::TransactionInput {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.from_public_key, serializer);
<Vec<u8>>::sse_encode(self.to_public_key, serializer);
<i64>::sse_encode(self.amount_micro_owc, serializer);
<String>::sse_encode(self.currency_context, serializer);
<String>::sse_encode(self.fx_rate_snapshot, serializer);
<i32>::sse_encode(self.channel, serializer);
<String>::sse_encode(self.memo, serializer);
<String>::sse_encode(self.device_id, serializer);
<Vec<u8>>::sse_encode(self.previous_nonce, serializer);
<Vec<u8>>::sse_encode(self.current_nonce, serializer);
<f64>::sse_encode(self.latitude, serializer);
<f64>::sse_encode(self.longitude, serializer);
<i32>::sse_encode(self.location_accuracy_meters, serializer);
<i32>::sse_encode(self.location_source, serializer);}
                }
                
                impl SseEncode for crate::api::transactions::TransactionView {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.transaction_id, serializer);
<Vec<u8>>::sse_encode(self.from_public_key, serializer);
<Vec<u8>>::sse_encode(self.to_public_key, serializer);
<i64>::sse_encode(self.amount_micro_owc, serializer);
<String>::sse_encode(self.currency_context, serializer);
<i64>::sse_encode(self.timestamp_utc, serializer);
<String>::sse_encode(self.memo, serializer);
<i32>::sse_encode(self.channel, serializer);
<String>::sse_encode(self.device_id, serializer);
<bool>::sse_encode(self.signature_valid, serializer);}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();

// Section: dart2rust

impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for *mut wire_cst_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
                unimplemented!()
            }
        }impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                let vec: Vec<u8> = self.cst_decode(); String::from_utf8(vec).unwrap()
            }
        }impl CstDecode<crate::api::transactions::TransactionInput> for *mut wire_cst_transaction_input {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::transactions::TransactionInput {
                let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
                CstDecode::<crate::api::transactions::TransactionInput>::cst_decode(*wrap).into()
            }
        }impl CstDecode<crate::api::crypto::Keypair> for wire_cst_keypair {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::crypto::Keypair {
                crate::api::crypto::Keypair{public_key:  self.public_key.cst_decode(),private_key:  self.private_key.cst_decode()}
            }
        }impl CstDecode<Vec<Vec<u8>>> for *mut wire_cst_list_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<Vec<u8>> {
                let vec = unsafe {
        let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
        flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
    };
    vec.into_iter().map(CstDecode::cst_decode).collect()
            }
        }impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                unsafe {
                    let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                    flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
                }
            }
        }impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                unsafe {
                    let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                    flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
                }
            }
        }impl CstDecode<crate::api::transactions::TransactionInput> for wire_cst_transaction_input {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::transactions::TransactionInput {
                crate::api::transactions::TransactionInput{from_public_key:  self.from_public_key.cst_decode(),to_public_key:  self.to_public_key.cst_decode(),amount_micro_owc:  self.amount_micro_owc.cst_decode(),currency_context:  self.currency_context.cst_decode(),fx_rate_snapshot:  self.fx_rate_snapshot.cst_decode(),channel:  self.channel.cst_decode(),memo:  self.memo.cst_decode(),device_id:  self.device_id.cst_decode(),previous_nonce:  self.previous_nonce.cst_decode(),current_nonce:  self.current_nonce.cst_decode(),latitude:  self.latitude.cst_decode(),longitude:  self.longitude.cst_decode(),location_accuracy_meters:  self.location_accuracy_meters.cst_decode(),location_source:  self.location_source.cst_decode()}
            }
        }impl CstDecode<crate::api::transactions::TransactionView> for wire_cst_transaction_view {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::transactions::TransactionView {
                crate::api::transactions::TransactionView{transaction_id:  self.transaction_id.cst_decode(),from_public_key:  self.from_public_key.cst_decode(),to_public_key:  self.to_public_key.cst_decode(),amount_micro_owc:  self.amount_micro_owc.cst_decode(),currency_context:  self.currency_context.cst_decode(),timestamp_utc:  self.timestamp_utc.cst_decode(),memo:  self.memo.cst_decode(),channel:  self.channel.cst_decode(),device_id:  self.device_id.cst_decode(),signature_valid:  self.signature_valid.cst_decode()}
            }
        }impl NewWithNullPtr for wire_cst_keypair {
            fn new_with_null_ptr() -> Self {
                Self { public_key: core::ptr::null_mut(),
private_key: core::ptr::null_mut(), }
            }
        }
        impl Default for wire_cst_keypair {
            fn default() -> Self {
                Self::new_with_null_ptr()
            }
        }impl NewWithNullPtr for wire_cst_transaction_input {
            fn new_with_null_ptr() -> Self {
                Self { from_public_key: core::ptr::null_mut(),
to_public_key: core::ptr::null_mut(),
amount_micro_owc: Default::default(),
currency_context: core::ptr::null_mut(),
fx_rate_snapshot: core::ptr::null_mut(),
channel: Default::default(),
memo: core::ptr::null_mut(),
device_id: core::ptr::null_mut(),
previous_nonce: core::ptr::null_mut(),
current_nonce: core::ptr::null_mut(),
latitude: Default::default(),
longitude: Default::default(),
location_accuracy_meters: Default::default(),
location_source: Default::default(), }
            }
        }
        impl Default for wire_cst_transaction_input {
            fn default() -> Self {
                Self::new_with_null_ptr()
            }
        }impl NewWithNullPtr for wire_cst_transaction_view {
            fn new_with_null_ptr() -> Self {
                Self { transaction_id: core::ptr::null_mut(),
from_public_key: core::ptr::null_mut(),
to_public_key: core::ptr::null_mut(),
amount_micro_owc: Default::default(),
currency_context: core::ptr::null_mut(),
timestamp_utc: Default::default(),
memo: core::ptr::null_mut(),
channel: Default::default(),
device_id: core::ptr::null_mut(),
signature_valid: Default::default(), }
            }
        }
        impl Default for wire_cst_transaction_view {
            fn default() -> Self {
                Self::new_with_null_ptr()
            }
        }

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__crypto__blake2b_256(port_: i64, data: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__crypto__blake2b_256_impl(port_, data)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__transactions__build_and_sign_transaction(port_: i64, input: *mut wire_cst_transaction_input, private_key: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__transactions__build_and_sign_transaction_impl(port_, input, private_key)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__wire__build_nfc_apdus(port_: i64, cbor: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__wire__build_nfc_apdus_impl(port_, cbor)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__transactions__decode_transaction(port_: i64, cbor: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__transactions__decode_transaction_impl(port_, cbor)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__transactions__derive_next_nonce(port_: i64, prev_nonce: *mut wire_cst_list_prim_u_8_loose, hardware_seed: *mut wire_cst_list_prim_u_8_loose, counter: u64)  {
                    wire__crate__api__transactions__derive_next_nonce_impl(port_, prev_nonce, hardware_seed, counter)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__crypto__generate_keypair(port_: i64)  {
                    wire__crate__api__crypto__generate_keypair_impl(port_)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__wire__qr_decode(port_: i64, qr: *mut wire_cst_list_prim_u_8_strict)  {
                    wire__crate__api__wire__qr_decode_impl(port_, qr)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__wire__qr_encode(port_: i64, cbor: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__wire__qr_encode_impl(port_, cbor)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__crypto__sign_message(port_: i64, message: *mut wire_cst_list_prim_u_8_loose, private_key: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__crypto__sign_message_impl(port_, message, private_key)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__crypto__user_id_from_public_key(port_: i64, public_key: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__crypto__user_id_from_public_key_impl(port_, public_key)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_wire__crate__api__crypto__verify_signature(port_: i64, message: *mut wire_cst_list_prim_u_8_loose, signature: *mut wire_cst_list_prim_u_8_loose, public_key: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__crypto__verify_signature_impl(port_, message, signature, public_key)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_cst_new_box_autoadd_transaction_input() -> *mut wire_cst_transaction_input {
                    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_transaction_input::new_with_null_ptr())
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_cst_new_list_list_prim_u_8_strict(len: i32) -> *mut wire_cst_list_list_prim_u_8_strict {
                    let wrap = wire_cst_list_list_prim_u_8_strict { ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(<*mut wire_cst_list_prim_u_8_strict>::new_with_null_ptr(), len), len };
                flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_cst_new_list_prim_u_8_loose(len: i32) -> *mut wire_cst_list_prim_u_8_loose {
                    let ans = wire_cst_list_prim_u_8_loose { ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len), len };
                    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
                }
            

                #[no_mangle]
                pub extern "C" fn frbgen_cylinder_seal_cst_new_list_prim_u_8_strict(len: i32) -> *mut wire_cst_list_prim_u_8_strict {
                    let ans = wire_cst_list_prim_u_8_strict { ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len), len };
                    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
                }
            
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_keypair { public_key: *mut wire_cst_list_prim_u_8_strict,
private_key: *mut wire_cst_list_prim_u_8_strict }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_list_list_prim_u_8_strict { ptr: *mut *mut wire_cst_list_prim_u_8_strict,
len: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_list_prim_u_8_loose { ptr: *mut u8,
len: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_list_prim_u_8_strict { ptr: *mut u8,
len: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_transaction_input { from_public_key: *mut wire_cst_list_prim_u_8_strict,
to_public_key: *mut wire_cst_list_prim_u_8_strict,
amount_micro_owc: i64,
currency_context: *mut wire_cst_list_prim_u_8_strict,
fx_rate_snapshot: *mut wire_cst_list_prim_u_8_strict,
channel: i32,
memo: *mut wire_cst_list_prim_u_8_strict,
device_id: *mut wire_cst_list_prim_u_8_strict,
previous_nonce: *mut wire_cst_list_prim_u_8_strict,
current_nonce: *mut wire_cst_list_prim_u_8_strict,
latitude: f64,
longitude: f64,
location_accuracy_meters: i32,
location_source: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_transaction_view { transaction_id: *mut wire_cst_list_prim_u_8_strict,
from_public_key: *mut wire_cst_list_prim_u_8_strict,
to_public_key: *mut wire_cst_list_prim_u_8_strict,
amount_micro_owc: i64,
currency_context: *mut wire_cst_list_prim_u_8_strict,
timestamp_utc: i64,
memo: *mut wire_cst_list_prim_u_8_strict,
channel: i32,
device_id: *mut wire_cst_list_prim_u_8_strict,
signature_valid: bool }
        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();

// Section: dart2rust

impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for String {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
                unimplemented!()
            }
        }impl CstDecode<String> for String {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                self
            }
        }impl CstDecode<crate::api::crypto::Keypair> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::crypto::Keypair {
                let self_ = self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap();
                assert_eq!(self_.length(), 2, "Expected 2 elements, got {}", self_.length());
                crate::api::crypto::Keypair{public_key:  self_.get(0).cst_decode(),private_key:  self_.get(1).cst_decode()}
            }
        }impl CstDecode<Vec<Vec<u8>>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<Vec<u8>> {
                self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap().iter().map(CstDecode::cst_decode).collect()
            }
        }impl CstDecode<Vec<u8>> for Box<[u8]> {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                self.into_vec()
            }
        }impl CstDecode<crate::api::transactions::TransactionInput> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::transactions::TransactionInput {
                let self_ = self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap();
                assert_eq!(self_.length(), 14, "Expected 14 elements, got {}", self_.length());
                crate::api::transactions::TransactionInput{from_public_key:  self_.get(0).cst_decode(),to_public_key:  self_.get(1).cst_decode(),amount_micro_owc:  self_.get(2).cst_decode(),currency_context:  self_.get(3).cst_decode(),fx_rate_snapshot:  self_.get(4).cst_decode(),channel:  self_.get(5).cst_decode(),memo:  self_.get(6).cst_decode(),device_id:  self_.get(7).cst_decode(),previous_nonce:  self_.get(8).cst_decode(),current_nonce:  self_.get(9).cst_decode(),latitude:  self_.get(10).cst_decode(),longitude:  self_.get(11).cst_decode(),location_accuracy_meters:  self_.get(12).cst_decode(),location_source:  self_.get(13).cst_decode()}
            }
        }impl CstDecode<crate::api::transactions::TransactionView> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::transactions::TransactionView {
                let self_ = self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap();
                assert_eq!(self_.length(), 10, "Expected 10 elements, got {}", self_.length());
                crate::api::transactions::TransactionView{transaction_id:  self_.get(0).cst_decode(),from_public_key:  self_.get(1).cst_decode(),to_public_key:  self_.get(2).cst_decode(),amount_micro_owc:  self_.get(3).cst_decode(),currency_context:  self_.get(4).cst_decode(),timestamp_utc:  self_.get(5).cst_decode(),memo:  self_.get(6).cst_decode(),channel:  self_.get(7).cst_decode(),device_id:  self_.get(8).cst_decode(),signature_valid:  self_.get(9).cst_decode()}
            }
        }impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
                unimplemented!()
            }
        }impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                self.as_string().expect("non-UTF-8 string, or not a string")
            }
        }impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> bool {
                self.is_truthy()
            }
        }impl CstDecode<f64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> f64 {
                self.unchecked_into_f64() as _
            }
        }impl CstDecode<i32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> i32 {
                self.unchecked_into_f64() as _
            }
        }impl CstDecode<i64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> i64 {
                ::std::convert::TryInto::<i64>::try_into(self).unwrap() as _
            }
        }impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>().to_vec().into()
            }
        }impl CstDecode<u64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u64 {
                ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
            }
        }impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u8 {
                self.unchecked_into_f64() as _
            }
        }

                #[wasm_bindgen]
                pub  fn wire__crate__api__crypto__blake2b_256(port_: flutter_rust_bridge::for_generated::MessagePort, data: Box<[u8]>)  {
                    wire__crate__api__crypto__blake2b_256_impl(port_, data)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__transactions__build_and_sign_transaction(port_: flutter_rust_bridge::for_generated::MessagePort, input: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue, private_key: Box<[u8]>)  {
                    wire__crate__api__transactions__build_and_sign_transaction_impl(port_, input, private_key)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__wire__build_nfc_apdus(port_: flutter_rust_bridge::for_generated::MessagePort, cbor: Box<[u8]>)  {
                    wire__crate__api__wire__build_nfc_apdus_impl(port_, cbor)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__transactions__decode_transaction(port_: flutter_rust_bridge::for_generated::MessagePort, cbor: Box<[u8]>)  {
                    wire__crate__api__transactions__decode_transaction_impl(port_, cbor)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__transactions__derive_next_nonce(port_: flutter_rust_bridge::for_generated::MessagePort, prev_nonce: Box<[u8]>, hardware_seed: Box<[u8]>, counter: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue)  {
                    wire__crate__api__transactions__derive_next_nonce_impl(port_, prev_nonce, hardware_seed, counter)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__crypto__generate_keypair(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                    wire__crate__api__crypto__generate_keypair_impl(port_)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__wire__qr_decode(port_: flutter_rust_bridge::for_generated::MessagePort, qr: String)  {
                    wire__crate__api__wire__qr_decode_impl(port_, qr)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__wire__qr_encode(port_: flutter_rust_bridge::for_generated::MessagePort, cbor: Box<[u8]>)  {
                    wire__crate__api__wire__qr_encode_impl(port_, cbor)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__crypto__sign_message(port_: flutter_rust_bridge::for_generated::MessagePort, message: Box<[u8]>, private_key: Box<[u8]>)  {
                    wire__crate__api__crypto__sign_message_impl(port_, message, private_key)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__crypto__user_id_from_public_key(port_: flutter_rust_bridge::for_generated::MessagePort, public_key: Box<[u8]>)  {
                    wire__crate__api__crypto__user_id_from_public_key_impl(port_, public_key)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__crypto__verify_signature(port_: flutter_rust_bridge::for_generated::MessagePort, message: Box<[u8]>, signature: Box<[u8]>, public_key: Box<[u8]>)  {
                    wire__crate__api__crypto__verify_signature_impl(port_, message, signature, public_key)
                }
            

        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        